# This workflow builds the book with documentation and runs book tests
name: Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: cargo build --verbose
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build the book
      run: mdbook build book
    - name: Run book tests
      run: mdbook test -L target/debug/deps book
